// Fichier GÉNÉRÉ par scripts/import_structures.py — ne pas modifier à la main.
// Source : cartographie-structures.xlsx (cartographie des structures de transfusion sanguine, Direction du CNTS).
import type { Structure } from "./structures";

export const STRUCTURES_DATA: Structure[] = [
  {"id": "centre-hospitalier-national-cheikh-ahmadoul-khadim", "name": "Centre Hospitalier National Cheikh Ahmadoul Khadim", "kind": "banque", "region": "SNDB", "departement": "Mbacké", "commune": "Touba", "hote": "Hôpital", "lat": 14.922855, "lng": -15.931234},
  {"id": "centre-hospitalier-national-matlaboul-fawzeyni-de-touba", "name": "Centre hospitalier national Matlaboul Fawzeyni de Touba", "kind": "banque", "region": "SNDB", "departement": "Mbacké", "commune": "Touba Mosquée", "hote": "Hôpital", "adresse": "Dianatou Mahwa", "repere": "Lekku Fi", "lat": 14.864865, "lng": -15.901537},
  {"id": "centre-hospitalier-regional-henrich-lubke-de-diourbel", "name": "Centre hospitalier régional Henrich Lubke de Diourbel", "kind": "banque", "region": "SNDB", "departement": "Diourbel", "commune": "Diourbel", "hote": "Hôpital", "adresse": "Thierno Kandji", "repere": "Stade de football", "lat": 14.6428, "lng": -16.232031},
  {"id": "poste-de-transfusion-sanguine-de-roi-baudouin", "name": "Poste de transfusion sanguine de Roi Baudouin", "kind": "banque", "region": "SNDK", "departement": "Guédiawaye", "commune": "Sam Notaire", "hote": "Hôpital", "adresse": "Sam Notaire", "repere": "Médina Gounass", "lat": 14.774849, "lng": -17.383391},
  {"id": "pts-hopital-dalal-jamm", "name": "PTS de l’Hôpital Dalal Jamm", "kind": "pts", "region": "SNDK", "departement": "Guédiawaye", "commune": "Golf Sud", "hote": "Hôpital", "adresse": "Golf Sud (Cité Aliou Sow)", "lat": 14.771973, "lng": -17.408179},
  {"id": "poste-de-transfusion-sanguine-de-rufisque", "name": "Poste de transfusion sanguine de Rufisque", "kind": "pts", "region": "SNDK", "departement": "Rufisque", "commune": "Rufisque Est", "hote": "PTS", "adresse": "Keury Kao", "repere": "District sanitaire", "lat": 14.712182, "lng": -17.272083},
  {"id": "chamfs-fatick", "name": "CHAMFS Fatick", "kind": "banque", "region": "SNFK", "departement": "Fatick", "commune": "Fatick", "hote": "Hôpital", "adresse": "Darell", "repere": "SENELEC", "lat": 14.344805, "lng": -16.414456},
  {"id": "centre-de-sante-sokone", "name": "Centre de santé Sokone", "kind": "banque", "region": "SNFK", "departement": "Foundiougne", "commune": "Sokone", "hote": "Centre de santé", "adresse": "Diamaguene Centre", "repere": "La Poste Finances", "lat": 13.878617, "lng": -16.368639},
  {"id": "centre-de-sante-gossas", "name": "Centre de santé Gossas", "kind": "depot", "region": "SNFK", "departement": "Gossas", "commune": "Gossas", "hote": "Centre de santé", "adresse": "Keur Khar", "repere": "Route Diourbel–Kaolack", "lat": 14.500031, "lng": -16.077391},
  {"id": "centre-de-sante-de-koungheul", "name": "Centre de santé de Koungheul", "kind": "banque", "region": "SNKA", "departement": "Koungheul", "commune": "Koungheul", "hote": "Centre de santé", "adresse": "Koungheul Ville", "repere": "Camp des sapeurs-pompiers", "lat": 13.981773, "lng": -14.791787},
  {"id": "centre-hospitalier-regional-de-kolda", "name": "Centre hospitalier régional de Kolda", "kind": "banque", "region": "SNKD", "departement": "Kolda", "commune": "Kolda", "hote": "Hôpital", "adresse": "Sare Moussa", "repere": "Près du Conseil départemental", "lat": 12.884736, "lng": -14.919264},
  {"id": "centre-hospitalier-regional-amath-dansokho-de-kedougou", "name": "Centre hospitalier régional Amath Dansokho de Kédougou", "kind": "banque", "region": "SNKE", "departement": "Kédougou", "commune": "Dimboli", "hote": "Hôpital", "lat": 12.538338, "lng": -12.150819},
  {"id": "crts-de-kaolack", "name": "CRTS de Kaolack", "kind": "crts", "region": "SNKL", "departement": "Kaolack", "commune": "Kaolack", "hote": "CRTS", "adresse": "Léona", "repere": "Hôpital El Hadji Ibrahima Niass", "lat": 14.141561, "lng": -16.07623},
  {"id": "centre-de-sante-de-nioro", "name": "Centre de santé de Nioro", "kind": "pts", "region": "SNKL", "departement": "Nioro", "commune": "Nioro", "hote": "Centre de santé", "adresse": "Nouroulaye", "repere": "Près du marché central", "lat": 13.742447, "lng": -15.779316},
  {"id": "chrasm-louga", "name": "CHRASM/Louga", "kind": "banque", "region": "SNLG", "departement": "Louga", "commune": "Louga", "hote": "Hôpital", "adresse": "Grand Louga", "repere": "Hôtel Kawsara", "lat": 15.616768, "lng": -16.236447},
  {"id": "hopital-magatte-lo-de-linguere", "name": "Hôpital Magatte LO de Linguère", "kind": "banque", "region": "SNLG", "departement": "Linguère", "commune": "Linguère", "hote": "Hôpital", "adresse": "Quartier Thiélly Nord", "repere": "À côté du Trésor public et du tribunal", "lat": 15.400598, "lng": -15.112576},
  {"id": "crts-de-matam", "name": "CRTS de Matam", "kind": "crts", "region": "SNMT", "departement": "Matam", "commune": "Matam", "hote": "CRTS", "adresse": "Tantadji", "repere": "Direction régionale de la santé", "lat": 15.660078, "lng": -13.263137},
  {"id": "centre-hospitalier-regional-de-ourossogui", "name": "Centre Hospitalier Régional de Ourossogui", "kind": "banque", "region": "SNMT", "departement": "Matam", "commune": "Ourossogui", "hote": "Hôpital", "adresse": "Moderne 3", "repere": "32ᵉ Bataillon", "lat": 15.603478, "lng": -13.329812},
  {"id": "centre-hospitalier-regional-amadou-tidiane-ba-de-sedhiou", "name": "Centre hospitalier régional Amadou Tidiane Ba de Sédhiou", "kind": "banque", "region": "SNSE", "departement": "Sédhiou", "commune": "Sédhiou", "hote": "Hôpital", "adresse": "Bambali, km 1 route de Marsassoum", "lat": 12.706091, "lng": -15.580301},
  {"id": "banque-de-sang-de-saint-louis", "name": "Banque de sang de Saint-Louis", "kind": "banque", "region": "SNSL", "departement": "Saint-Louis", "commune": "Saint-Louis", "hote": "Banque de sang", "adresse": "Corniche Sor", "repere": "Sen'Eau de Saint-Louis", "lat": 16.025333, "lng": -16.489342},
  {"id": "centre-de-sante-bakel", "name": "Centre de santé Bakel", "kind": "banque", "region": "SNTC", "departement": "Bakel", "commune": "Bakel", "hote": "Centre de santé", "adresse": "HLM Bakel", "repere": "Camp des sapeurs-pompiers", "lat": 14.915087, "lng": -12.457409},
  {"id": "centre-hospitalier-regional-de-tambacounda", "name": "Centre hospitalier régional de Tambacounda", "kind": "banque", "region": "SNTC", "departement": "Tambacounda", "commune": "Tambacounda", "hote": "Hôpital", "adresse": "Diallo Bougou", "repere": "Camp militaire, en face de l'armée de l'air", "lat": 13.753039, "lng": -13.672984},
  {"id": "centre-hospitalier-mame-abdou-aziz-de-tivaouane", "name": "Centre Hospitalier Mame Abdou Aziz de Tivaouane", "kind": "banque", "region": "SNTH", "departement": "Tivaouane", "commune": "Tivaouane", "hote": "Hôpital", "adresse": "Ainoumasy", "lat": 14.945129, "lng": -16.825397},
  {"id": "centre-hospitalier-regional-de-thies", "name": "Centre Hospitalier Régional de Thiès", "kind": "banque", "region": "SNTH", "departement": "Thiès", "commune": "Thiès", "hote": "Hôpital", "adresse": "Avenue Malick Sy Prolongée", "repere": "Pharmacie Serigne Saliou Mbacké et SGS", "lat": 14.781095, "lng": -16.924215},
  {"id": "centre-hospitalier-thierno-mouhamadoul-mansour-barro", "name": "Centre hospitalier Thierno Mouhamadoul Mansour BARRO", "kind": "banque", "region": "SNTH", "departement": "Mbour", "commune": "Mbour", "hote": "Hôpital", "adresse": "Grand Mbour", "repere": "ENDA", "lat": 14.422443, "lng": -16.985765},
  {"id": "centre-de-sante-fiacre-coly-de-khombole", "name": "Centre de santé Fiacre Coly de Khombole", "kind": "depot", "region": "SNTH", "departement": "Thiès", "commune": "Khombole", "hote": "Centre de santé", "adresse": "Keur Macodou", "repere": "Route nationale, angle Touba Toul", "lat": 14.761145, "lng": -16.683578},
  {"id": "centre-hospitalier-regional-de-ziguinchor", "name": "Centre Hospitalier Régional de Ziguinchor", "kind": "banque", "region": "SNZG", "departement": "Ziguinchor", "commune": "Ziguinchor", "hote": "Hôpital", "adresse": "HLM NEMA", "repere": "Aéroport de Ziguinchor", "lat": 12.55764, "lng": -16.282479},
  {"id": "service-hematologie-banque-de-sang-de-ziguinchor", "name": "Service hématologie banque de sang de Ziguinchor", "kind": "banque", "region": "SNZG", "departement": "Ziguinchor", "commune": "Ziguinchor", "hote": "Hôpital", "adresse": "Kadior", "lat": 12.569576, "lng": -16.276522},
];
