"""add_missing_donor_fields

Revision ID: 1a385b40d921
Revises: 7eaf099625e6
Create Date: 2026-02-03 15:54:08.780919

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1a385b40d921'
down_revision = '7eaf099625e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donneurs', sa.Column('region', sa.String(length=64), nullable=True))
    op.add_column('donneurs', sa.Column('departement', sa.String(length=64), nullable=True))
    op.add_column('donneurs', sa.Column('profession', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donneurs', 'profession')
    op.drop_column('donneurs', 'departement')
    op.drop_column('donneurs', 'region')
    # ### end Alembic commands ###
