"""Add Article model

Revision ID: 61af3582e78d
Revises: 7c82261f596f
Create Date: 2026-02-03 20:46:52.230281

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '61af3582e78d'
down_revision = '7c82261f596f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_is_published'), 'articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.drop_index(op.f('ix_donneurs_groupe_sanguin'), table_name='donneurs')
    op.drop_index(op.f('ix_donneurs_region'), table_name='donneurs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_donneurs_region'), 'donneurs', ['region'], unique=False)
    op.create_index(op.f('ix_donneurs_groupe_sanguin'), 'donneurs', ['groupe_sanguin'], unique=False)
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_published'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
