"""add_donor_details

Revision ID: 7eaf099625e6
Revises: 0011_auth_users_2fa
Create Date: 2026-02-03 14:24:45.337091

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7eaf099625e6'
down_revision = '0011_auth_users_2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actes_transfusionnels', 'date_transfusion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('actes_transfusionnels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_actes_transfusionnels_poche_id'), 'actes_transfusionnels', type_='unique')
    op.drop_index(op.f('ix_actes_transfusionnels_poche_id'), table_name='actes_transfusionnels')
    op.create_index(op.f('ix_actes_transfusionnels_poche_id'), 'actes_transfusionnels', ['poche_id'], unique=True)
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'date_demande',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cross_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_cross_matches_poche_receveur'), 'cross_matches', type_='unique')
    op.add_column('donneurs', sa.Column('cni', sa.String(length=64), nullable=True))
    op.add_column('donneurs', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('donneurs', sa.Column('groupe_sanguin', sa.String(length=8), nullable=True))
    op.add_column('donneurs', sa.Column('adresse', sa.String(length=255), nullable=True))
    op.add_column('donneurs', sa.Column('telephone', sa.String(length=32), nullable=True))
    op.add_column('donneurs', sa.Column('email', sa.String(length=120), nullable=True))
    op.alter_column('donneurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('donneurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_donneurs_cni_hash'), 'donneurs', type_='unique')
    op.drop_index(op.f('ix_donneurs_cni_hash'), table_name='donneurs')
    op.create_index(op.f('ix_donneurs_cni_hash'), 'donneurs', ['cni_hash'], unique=True)
    op.alter_column('dons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_dons_din'), 'dons', type_='unique')
    op.drop_index(op.f('ix_dons_din'), table_name='dons')
    op.create_index(op.f('ix_dons_din'), 'dons', ['din'], unique=True)
    op.alter_column('fractionnement_recettes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hopitaux', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_hopitaux_nom'), 'hopitaux', type_='unique')
    op.drop_index(op.f('ix_hopitaux_nom'), table_name='hopitaux')
    op.create_index(op.f('ix_hopitaux_nom'), 'hopitaux', ['nom'], unique=True)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_idempotency_scope_key'), table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_scope'), 'idempotency_keys', ['scope'], unique=False)
    op.alter_column('poches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappel_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('receveurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reservations', 'date_reservation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_reservations_poche_id'), 'reservations', type_='unique')
    op.create_index(op.f('ix_reservations_poche_id'), 'reservations', ['poche_id'], unique=True)
    op.alter_column('sync_devices', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_sync_devices_device_id'), 'sync_devices', type_='unique')
    op.drop_index(op.f('ix_sync_devices_device_id'), table_name='sync_devices')
    op.create_index(op.f('ix_sync_devices_device_id'), 'sync_devices', ['device_id'], unique=True)
    op.alter_column('sync_ingested_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trace_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_user_accounts_email'), 'user_accounts', type_='unique')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.alter_column('user_recovery_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_recovery_codes_user_id_fkey'), 'user_recovery_codes', type_='foreignkey')
    op.create_foreign_key(None, 'user_recovery_codes', 'user_accounts', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_recovery_codes', type_='foreignkey')
    op.create_foreign_key(op.f('user_recovery_codes_user_id_fkey'), 'user_recovery_codes', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_recovery_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_user_accounts_email'), 'user_accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trace_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_ingested_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sync_devices_device_id'), table_name='sync_devices')
    op.create_index(op.f('ix_sync_devices_device_id'), 'sync_devices', ['device_id'], unique=False)
    op.create_unique_constraint(op.f('uq_sync_devices_device_id'), 'sync_devices', ['device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('sync_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_devices', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reservations_poche_id'), table_name='reservations')
    op.create_unique_constraint(op.f('uq_reservations_poche_id'), 'reservations', ['poche_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reservations', 'date_reservation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('receveurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rappel_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('poches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_idempotency_keys_scope'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_scope_key'), 'idempotency_keys', ['scope', 'key'], unique=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_hopitaux_nom'), table_name='hopitaux')
    op.create_index(op.f('ix_hopitaux_nom'), 'hopitaux', ['nom'], unique=False)
    op.create_unique_constraint(op.f('uq_hopitaux_nom'), 'hopitaux', ['nom'], postgresql_nulls_not_distinct=False)
    op.alter_column('hopitaux', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fractionnement_recettes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dons_din'), table_name='dons')
    op.create_index(op.f('ix_dons_din'), 'dons', ['din'], unique=False)
    op.create_unique_constraint(op.f('uq_dons_din'), 'dons', ['din'], postgresql_nulls_not_distinct=False)
    op.alter_column('dons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_donneurs_cni_hash'), table_name='donneurs')
    op.create_index(op.f('ix_donneurs_cni_hash'), 'donneurs', ['cni_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_donneurs_cni_hash'), 'donneurs', ['cni_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('donneurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('donneurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('donneurs', 'email')
    op.drop_column('donneurs', 'telephone')
    op.drop_column('donneurs', 'adresse')
    op.drop_column('donneurs', 'groupe_sanguin')
    op.drop_column('donneurs', 'date_naissance')
    op.drop_column('donneurs', 'cni')
    op.create_unique_constraint(op.f('uq_cross_matches_poche_receveur'), 'cross_matches', ['poche_id', 'receveur_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cross_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commandes', 'date_demande',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_actes_transfusionnels_poche_id'), table_name='actes_transfusionnels')
    op.create_index(op.f('ix_actes_transfusionnels_poche_id'), 'actes_transfusionnels', ['poche_id'], unique=False)
    op.create_unique_constraint(op.f('uq_actes_transfusionnels_poche_id'), 'actes_transfusionnels', ['poche_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('actes_transfusionnels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('actes_transfusionnels', 'date_transfusion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
