"""Add expiration_rules table

Revision ID: a7b686c3d949
Revises: a9c685b6b025
Create Date: 2026-02-03 23:46:35.709372

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a7b686c3d949'
down_revision = 'a9c685b6b025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expiration_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('preservation_type', sa.String(length=32), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('shelf_life_value', sa.Integer(), nullable=False),
    sa.Column('shelf_life_unit', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expiration_rules_product_type'), 'expiration_rules', ['product_type'], unique=False)
    op.drop_column('donneurs', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donneurs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_expiration_rules_product_type'), table_name='expiration_rules')
    op.drop_table('expiration_rules')
    # ### end Alembic commands ###
