"""Add Patient Space models

Revision ID: a9c685b6b025
Revises: 61af3582e78d
Create Date: 2026-02-03 21:06:37.839805

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a9c685b6b025'
down_revision = '61af3582e78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_medicaux',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donneur_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('type_document', sa.String(length=32), nullable=False),
    sa.Column('fichier_url', sa.String(length=500), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donneur_id'], ['donneurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_medicaux_donneur_id'), 'documents_medicaux', ['donneur_id'], unique=False)
    op.create_table('rendez_vous',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donneur_id', sa.UUID(), nullable=False),
    sa.Column('date_prevue', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_rdv', sa.String(length=32), nullable=False),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('lieu', sa.String(length=120), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donneur_id'], ['donneurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendez_vous_date_prevue'), 'rendez_vous', ['date_prevue'], unique=False)
    op.create_index(op.f('ix_rendez_vous_donneur_id'), 'rendez_vous', ['donneur_id'], unique=False)
    op.add_column('donneurs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_donneurs_user_id'), 'donneurs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'donneurs', 'user_accounts', ['user_id'], ['id'])
    op.add_column('user_accounts', sa.Column('role', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_user_accounts_role'), 'user_accounts', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_role'), table_name='user_accounts')
    op.drop_column('user_accounts', 'role')
    op.drop_constraint(None, 'donneurs', type_='foreignkey')
    op.drop_index(op.f('ix_donneurs_user_id'), table_name='donneurs')
    op.drop_column('donneurs', 'user_id')
    op.drop_index(op.f('ix_rendez_vous_donneur_id'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_date_prevue'), table_name='rendez_vous')
    op.drop_table('rendez_vous')
    op.drop_index(op.f('ix_documents_medicaux_donneur_id'), table_name='documents_medicaux')
    op.drop_table('documents_medicaux')
    # ### end Alembic commands ###
