"""Restore donneurs updated_at

Revision ID: ed7185b7458a
Revises: a7b686c3d949
Create Date: 2026-02-03 23:52:35.522562

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ed7185b7458a'
down_revision = 'a7b686c3d949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donneurs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donneurs', 'updated_at')
    # ### end Alembic commands ###
